name: bioTools
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - boost=1.74.0=py36h355b2fd_3
  - boost-cpp=1.74.0=hc6e9bd1_3
  - bzip2=1.0.8=h7b6447c_0
  - certifi=2016.2.28=py36_0
  - htstream=1.3.3=hec69f7e_1
  - icu=68.1=h2531618_0
  - intel-openmp=2021.2.0=h06a4308_610
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h2828fa1_19
  - libstdcxx-ng=9.3.0=h6de172a_19
  - lz4-c=1.9.3=h2531618_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.0.14=py36hd81dba3_0
  - mkl_random=1.0.4=py36hd81dba3_0
  - numpy=1.17.0=py36h7e9f1db_0
  - numpy-base=1.17.0=py36hde5b4d6_0
  - openssl=1.0.2l=0
  - pip=9.0.1=py36_1
  - python=3.6.2=0
  - python_abi=3.6=1_cp36m
  - readline=6.2=2
  - setuptools=36.4.0=py36_1
  - six=1.10.0=py36_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.29.0=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=0
  - zstd=1.4.9=haebb681_0
prefix: /public/home/xyhuang/anaconda3/envs/bioTools
