name: circos
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - circos=0.69.6=4
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - giflib=5.1.4=h14c3975_1
  - icu=58.2=h9c2bf20_1
  - jpeg=9b=h024ee3a_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgd=2.2.5=hceca4fd_3
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libwebp=1.0.1=h8e7db2f_0
  - libxml2=2.9.9=he19cac6_0
  - perl=5.26.2=h14c3975_0
  - perl-autoloader=5.74=pl526_2
  - perl-carp=1.38=pl526_2
  - perl-clone=0.41=pl526h470a237_0
  - perl-config-general=2.63=pl526_0
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-dynaloader=1.25=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.34=pl526_3
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.70=pl526he941832_0
  - perl-io-string=1.08=pl526_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-math-bezier=0.01=pl526_1
  - perl-math-round=0.07=pl526_1
  - perl-math-vecstat=0.08=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_0
  - perl-number-format=1.75=pl526_3
  - perl-params-validate=1.29=pl526h470a237_0
  - perl-pathtools=3.75=pl526h14c3975_0
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-scalar-list-utils=1.45=pl526h470a237_3
  - perl-set-intspan=1.19=pl526_1
  - perl-statistics-basic=1.6611=pl526_2
  - perl-svg=2.84=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-time-hires=1.9758=pl526_0
  - perl-try-tiny=0.30=pl526_1
  - perl-xml-parser=2.44=pl526h3a4f0e9_6
  - perl-xsloader=0.24=pl526_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /public/home/xyhuang/anaconda3/envs/circos
