name: deeptools
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py36h06a4308_0
  - curl=7.54.1=0
  - cycler=0.10.0=py36_0
  - decorator=4.1.2=py36_0
  - deeptools=3.5.1=py_0
  - deeptoolsintervals=0.1.9=py36h516909a_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2021.2.0=h06a4308_610
  - ipython_genutils=0.2.0=py36_0
  - jpeg=9b=0
  - jsonschema=2.6.0=py36_0
  - jupyter_core=4.3.0=py36_0
  - kiwisolver=1.3.1=py36h2531618_0
  - krb5=1.13.2=0
  - lcms2=2.12=h3be6417_0
  - libcurl=7.61.1=heec0ca6_0
  - libdeflate=1.0=h14c3975_1
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.8.0=0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - matplotlib-base=3.3.4=py36h62a2d02_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.0.14=py36hd81dba3_0
  - mkl_random=1.0.4=py36hd81dba3_0
  - nbformat=4.4.0=py36_0
  - numpy=1.17.0=py36h7e9f1db_0
  - numpy-base=1.17.0=py36hde5b4d6_0
  - olefile=0.44=py36_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.0.2u=h7b6447c_0
  - pillow=8.3.1=py36h2c7a002_0
  - pip=9.0.1=py36_1
  - plotly=2.0.11=py36_0
  - py2bit=0.3.0=py36h14c3975_2
  - pybigwig=0.3.13=py36h92ddc84_1
  - pyparsing=2.2.0=py36_0
  - pysam=0.15.3=py36hda2845c_1
  - python=3.6.2=0
  - python-dateutil=2.6.1=py36_0
  - pytz=2017.2=py36_0
  - readline=6.2=2
  - requests=2.14.2=py36_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=36.4.0=py36_1
  - six=1.10.0=py36_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - tornado=4.5.2=py36_0
  - traitlets=4.3.2=py36_0
  - wheel=0.29.0=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=0
  - zstd=1.4.9=haebb681_0
prefix: /public/home/xyhuang/anaconda3/envs/deeptools
