name: hapcut2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2016.2.28=py36_0
  - hapcut2=1.3.3=h6233b05_2
  - htslib=1.14=h9093b5e_0
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.82.0=h0b77cf5_0
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.2.1=1
  - libgcc-ng=12.1.0=h8d9b700_16
  - libnghttp2=1.46.0=hce63b2e_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libzlib=1.2.12=h166bdaf_2
  - llvm-openmp=14.0.4=he0ac6c6_0
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=9.0.1=py36_1
  - pysam=0.17.0=py36h61e5637_0
  - python=3.6.10=hcf32534_1
  - python_abi=3.6=2_cp36m
  - readline=8.1.2=h7f8727e_1
  - setuptools=36.4.0=py36_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.29.0=py36_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
prefix: /public/home/xyhuang/anaconda3/envs/hapcut2
