name: macs2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _r-mutex=1.0.0=anacondar_1
  - blas=1.0=mkl
  - bzip2=1.0.6=3
  - cairo=1.14.8=0
  - certifi=2016.2.28=py36_0
  - curl=7.54.1=0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.50.2=1
  - gsl=2.2.1=0
  - harfbuzz=0.9.39=2
  - icu=54.1=0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jbig=2.1=0
  - jpeg=9b=0
  - krb5=1.13.2=0
  - libffi=3.2.1=1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libiconv=1.14=0
  - libpng=1.6.30=1
  - libssh2=1.8.0=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.0.6=3
  - libxml2=2.9.4=0
  - llvm-openmp=14.0.6=h9e868ea_0
  - macs2=2.2.7.1=py36h91eb985_5
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.0.14=py36hd81dba3_0
  - mkl_random=1.0.4=py36hd81dba3_0
  - ncurses=5.9=10
  - numpy=1.17.0=py36h7e9f1db_0
  - numpy-base=1.17.0=py36hde5b4d6_0
  - openssl=1.0.2l=0
  - pango=1.40.3=1
  - pcre=8.39=1
  - pip=9.0.1=py36_1
  - pixman=0.34.0=0
  - python=3.6.2=0
  - python_abi=3.6=2_cp36m
  - r-base=3.4.1=1
  - readline=6.2=2
  - setuptools=36.4.0=py36_1
  - six=1.10.0=py36_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.29.0=py36_0
  - xz=5.2.3=0
  - zlib=1.2.13=h5eee18b_0
prefix: /public/home/xyhuang/anaconda3/envs/macs2
