name: pymol
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - schrodinger
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - apbs=1.5=h14c3975_3
  - blas=1.0=mkl
  - certifi=2016.2.28=py27_0
  - dbus=1.10.22=h3b5a359_0
  - expat=2.1.0=0
  - fontconfig=2.12.4=h88586e7_1
  - freemol=1.158=py27_0
  - freetype=2.8=hab7d2ae_1
  - glew=2.0.0=0
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - h5py=2.7.0=np113py27_0
  - hdf5=1.8.17=2
  - icu=58.2=h9c2bf20_1
  - jpeg=9b=0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.14=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.9=he85c1e1_1
  - libxcb=1.12=1
  - libxml2=2.9.4=0
  - mengine=1=h14c3975_1
  - mkl=2017.0.3=0
  - mpeg_encode=1=h14c3975_1
  - mtz2ccp4_px=1.0=1
  - ncurses=6.1=he6710b0_1
  - numpy=1.13.1=py27_0
  - olefile=0.44=py27_0
  - openblas=0.2.19=0
  - openssl=1.0.2l=0
  - pcre=8.39=1
  - pdb2pqr=2.1.1=py27_1
  - pillow=4.2.1=py27h7cd2321_0
  - pip=9.0.1=py27_1
  - pmw=2.0.1=py27_2
  - pymol=2.3.2=py27h75f9260_0
  - pyqt=5.6.0=py27_2
  - python=2.7.11=0
  - qt=5.6.2=h974d657_12
  - readline=6.2=2
  - requests=2.14.2=py27_0
  - rigimol=1.3=2
  - setuptools=36.4.0=py27_1
  - sip=4.18=py27_0
  - six=1.10.0=py27_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.5.18=0
  - wheel=0.29.0=py27_0
  - xz=5.2.3=0
  - zlib=1.2.11=0
prefix: /public/home/xyhuang/anaconda3/envs/pymol
