name: python27
channels:
  - esgf
  - ieguinoa
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - bcftools=1.3.1=h84994c4_5
  - blas=1.0=mkl
  - bowtie2=2.3.4.3=py27he860b03_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.5.15=1
  - cairo=1.14.8=0
  - curl=7.54.1=0
  - cycler=0.10.0=py27_0
  - deeptools=2.5.0=py27_0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - glib=2.50.2=1
  - harfbuzz=0.9.39=2
  - htslib=1.3.2=0
  - krb5=1.13.2=0
  - libdeflate=1.0=h14c3975_1
  - libffi=3.2.1=hf484d3e_1005
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libiconv=1.14=0
  - libpng=1.6.30=1
  - libssh2=1.8.0=0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libxml2=2.9.4=0
  - matplotlib=1.5.1=np111py27_0
  - mkl=2017.0.3=0
  - ncurses=6.1=hf484d3e_1002
  - openssl=1.0.2l=0
  - pango=1.40.3=1
  - pcre=8.39=1
  - perl=5.26.2=h14c3975_0
  - pip=19.0.1=py27_0
  - pixman=0.34.0=0
  - py2bit=0.3.0=py27h14c3975_2
  - pybigwig=0.2.8=py27_0
  - pycairo=1.10.0=py27_0
  - pyparsing=2.2.0=py27_0
  - pyqt=4.11.4=py27_4
  - pysam=0.15.3=py27hda2845c_1
  - python=2.7.13=0
  - python-dateutil=2.6.1=py27_0
  - pytz=2017.2=py27_0
  - qt=4.8.7=4
  - readline=6.2=2
  - samtools=1.3.1=0
  - setuptools=36.4.0=py27_1
  - sip=4.18=py27_0
  - sqlite=3.13.0=0
  - tbb=2019.4=hfd86e86_0
  - tk=8.5.18=0
  - wheel=0.32.3=py27_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h14c3975_1004
  - pip:
    - alabaster==0.7.12
    - babel==2.9.1
    - biopython==1.74
    - bx-python==0.8.2
    - certifi==2021.5.30
    - chardet==4.0.0
    - cpat==1.2.4
    - docutils==0.17.1
    - idna==2.10
    - imagesize==1.2.0
    - jinja2==2.11.3
    - macs2==2.1.2
    - markupsafe==1.1.1
    - numpy==1.16.2
    - numpydoc==0.9.2
    - packaging==20.9
    - pybedtools==0.8.0
    - pygments==2.5.2
    - regex==2019.12.20
    - requests==2.26.0
    - scikit-learn==0.20.4
    - scipy==1.2.1
    - six==1.12.0
    - snowballstemmer==2.1.0
    - sphinx==1.8.5
    - sphinxcontrib-websupport==1.1.2
    - typing==3.10.0.0
    - urllib3==1.26.6
prefix: /public/home/xyhuang/anaconda3/envs/python27
