name: RNAfold
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.2.1=1
  - libgcc-ng=12.2.0=h65d4601_19
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=14.0.6=h9e868ea_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - perl=5.32.1=0_h5eee18b_perl5
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.2=hcf32534_0
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - viennarna=2.5.1=py38pl5321h5cf8b27_2
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h166bdaf_4
prefix: /public/home/xyhuang/anaconda3/envs/RNAfold
