name: base
channels:
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.1.0=py310h06a4308_0
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=2.0.2=py310h06a4308_0
  - conda-package-streaming=0.7.0=py310h06a4308_0
  - cryptography=38.0.4=py310h9ce1e76_0
  - idna=3.4=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - tqdm=4.64.1=py310h06a4308_0
  - urllib3=1.26.14=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.18.0=py310h5eee18b_0
  - pip:
      - alabaster==0.7.13
      - anndata==0.9.1
      - annoy==1.16.0
      - args==0.1.0
      - asciitree==0.3.3
      - asttokens==2.2.1
      - babel==2.12.1
      - backcall==0.2.0
      - bbknn==1.6.0
      - bioframe==0.4.1
      - biopython==1.79
      - blosc2==2.0.0
      - bx-python==0.8.13
      - bz2file==0.98
      - chardet==5.2.0
      - click==8.1.3
      - clint==0.5.1
      - cloudpickle==3.1.0
      - coloredlogs==15.0.1
      - colormath==3.0.0
      - contourpy==1.0.7
      - cooler==0.8.2
      - coverage==7.5.4
      - crossmap==0.6.1
      - cutadapt==4.3
      - cycler==0.11.0
      - cython==0.29.33
      - cytoolz==0.12.1
      - decorator==5.1.1
      - deeptools==3.5.5
      - deeptoolsintervals==0.1.9
      - deprecated==1.2.13
      - dill==0.3.6
      - dnaio==0.10.0
      - docutils==0.19
      - drmaa==0.7.9
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fanc==0.9.28
      - fonttools==4.39.0
      - future==0.18.3
      - gatktool==0.0.1
      - genomic-regions==0.0.10
      - gridmap==0.15.0
      - h5py==3.8.0
      - harmonypy==0.0.9
      - hic2cool==0.5.1
      - hicexplorer==2.2.1.1
      - hicmatrix==7
      - hicrep==0.2.6
      - htseq==2.0.5
      - humanfriendly==10.0
      - iced==0.5.10
      - igraph==0.10.5
      - imageio==2.34.2
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - iniconfig==2.0.0
      - intervaltree==2.1.0
      - ipython==8.13.2
      - isal==1.1.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.3.1
      - kaleido==0.2.1
      - khmer==2.1.1
      - kiwisolver==1.4.4
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - llvmlite==0.40.1
      - loompy==3.0.7
      - lzstring==1.0.4
      - macs2==2.2.9.1
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.2
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - matplotlib-venn==0.11.9
      - mdurl==0.1.2
      - msgpack==1.0.5
      - msgpack-numpy==0.4.8
      - multiprocess==0.70.14
      - multiqc==1.16
      - natsort==8.4.0
      - networkx==3.1
      - nose==1.3.7
      - numba==0.57.1
      - numexpr==2.8.4
      - numpy==1.23.0
      - numpy-groupies==0.11.1
      - numpydoc==1.5.0
      - packaging==23.0
      - pairtools==1.0.2
      - pandas==2.0.1
      - pandoc==2.4
      - parso==0.8.3
      - patsy==0.5.6
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==3.8.0
      - plotly==5.13.1
      - plumbum==1.9.0
      - ply==3.11
      - polars==0.18.0
      - pooch==1.7.0
      - progressbar2==4.5.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - py2bit==0.3.0
      - pyarrow==12.0.1
      - pybedtools==0.10.0
      - pybigwig==0.3.20
      - pybktree==1.1
      - pyfaidx==0.7.2.1
      - pygenometracks==3.0
      - pygments==2.14.0
      - pynndescent==0.5.10
      - pypairix==0.3.7
      - pyparsing==3.0.9
      - pysam==0.20.0
      - pytest==7.3.1
      - python-dateutil==2.8.2
      - python-utils==3.9.0
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==26.2.0
      - regex==2023.6.3
      - rich==13.6.0
      - rich-click==1.6.1
      - rustworkx==0.13.0
      - scanpy==1.10.2
      - scikit-image==0.24.0
      - scikit-learn==1.3.0
      - scipy==1.11.3
      - screed==1.1.2
      - seaborn==0.13.2
      - seqtk==0.5.0
      - session-info==1.0.0
      - setuptools==57.5.0
      - snapatac2==2.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - spark-parser==1.8.9
      - spatialid==1.0.3
      - spectra==0.0.11
      - sphinx==6.1.3
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.2
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - tables==3.8.0
      - tabulate==0.9.0
      - tenacity==8.2.2
      - term-background==1.0.1
      - texttable==1.6.7
      - threadpoolctl==3.1.0
      - tifffile==2024.6.18
      - tomli==2.0.1
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - umap-learn==0.5.6
      - umi-tools==1.1.4
      - uncompyle==2.0.0
      - uncompyle6==3.9.1
      - unidecode==1.3.6
      - wcwidth==0.2.6
      - wrapt==1.15.0
      - xdis==6.1.0
      - xopen==1.7.0
      - zipp==3.17.0
prefix: /data/home/ruanlab/huangxingyu/miniconda3
