name: alfred
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alfred=0.2.8=h0d5efe1_0
  - biopython=1.68=np111py27_0
  - blas=1.0=mkl
  - boost-cpp=1.78.0=h2c5509c_4
  - bx-python=0.7.3=py27_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cairo=1.14.8=0
  - certifi=2016.2.28=py27_0
  - curl=7.26.0=1
  - cycler=0.10.0=py27_0
  - fontconfig=2.12.1=3
  - freetype=2.5.5=2
  - hdf5=1.8.17=2
  - hicexplorer=1.3=py27_0
  - htslib=1.19=h81da01d_0
  - icu=73.2=h59595ed_0
  - krb5=1.20.1=h143b758_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.2.1=1
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran=3.0.0=1
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.14=0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.30=1
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libxml2=2.9.4=0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=1.5.1=np111py27_0
  - mkl=2017.0.3=0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.6.2=np111py27_0
  - numpy=1.11.3=py27_0
  - openssl=3.2.0=hd590300_1
  - pip=9.0.1=py27_1
  - pixman=0.34.0=0
  - pybigwig=0.2.8=py27_0
  - pycairo=1.10.0=py27_0
  - pyparsing=2.2.0=py27_0
  - pyqt=4.11.4=py27_4
  - pysam=0.8.4=py27_0
  - pytables=3.3.0=np111py27_0
  - python=2.7.18=h02575d3_0
  - python-dateutil=2.6.1=py27_0
  - pytz=2017.2=py27_0
  - qt=4.8.7=2
  - readline=8.2=h5eee18b_0
  - scipy=0.19.0=np111py27_0
  - setuptools=36.4.0=py27_1
  - sip=4.18=py27_0
  - six=1.10.0=py27_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.29.0=py27_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/alfred
