name: GDAL
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - affine=2.4.0=pyhd8ed1ab_0
  - array-api-compat=1.7.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.22=h96bc93b_2
  - aws-c-cal=0.6.14=h88a6e22_1
  - aws-c-common=0.9.19=h4ab18f5_0
  - aws-c-compression=0.2.18=h83b837d_6
  - aws-c-event-stream=0.4.2=ha47c788_12
  - aws-c-http=0.8.1=h29d6fba_17
  - aws-c-io=0.14.8=h21d4f22_5
  - aws-c-mqtt=0.10.4=h759edc4_4
  - aws-c-s3=0.5.9=h594631b_3
  - aws-c-sdkutils=0.1.16=h83b837d_2
  - aws-checksums=0.1.18=h83b837d_6
  - aws-crt-cpp=0.26.9=he3a8b3b_0
  - aws-sdk-cpp=1.11.329=hba8bd5f_3
  - azure-core-cpp=1.11.1=h91d86a7_1
  - azure-identity-cpp=1.6.0=hf1915f5_1
  - azure-storage-blobs-cpp=12.10.0=h00ab1b0_1
  - azure-storage-common-cpp=12.5.0=h94269e2_4
  - binutils_impl_linux-64=2.40=ha1999f0_1
  - blosc=1.21.5=hc2324a3_1
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cfitsio=4.4.0=hbdc6101_1
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - curl=8.8.0=he654da7_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - expat=2.6.2=h59595ed_0
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.2.0=h9eb54c0_7
  - gdal=3.8.5=py312h86af8fa_7
  - geos=3.12.1=h59595ed_0
  - geotiff=1.7.3=h928be8b_0
  - gfortran_impl_linux-64=13.2.0=h738fc78_7
  - giflib=5.2.2=hd590300_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h59595ed_1
  - graphite2=1.3.13=h59595ed_1003
  - gxx_impl_linux-64=13.2.0=h2a599c4_7
  - h5py=3.11.0=nompi_py312hb7ab980_101
  - harfbuzz=8.5.0=hfac3d4d_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_103
  - icu=73.2=h59595ed_0
  - json-c=0.17=h7ab15ed_0
  - kealib=1.5.3=hee9dde6_1
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=22_linux64_openblas
  - libboost-headers=1.85.0=ha770c72_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.8.0=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=hceb6213_107
  - libgcc-ng=13.2.0=h77fa898_7
  - libgdal=3.8.5=h77540a9_7
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.2=hf974151_0
  - libgomp=13.2.0=h77fa898_7
  - libgoogle-cloud=2.24.0=h2736e30_0
  - libgoogle-cloud-storage=2.24.0=h3d9a0c8_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkml=1.3.0=h01aab08_1018
  - liblapack=3.9.0=22_linux64_openblas
  - libnetcdf=4.9.2=nompi_h9612171_113
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - librttopo=1.1.0=h8917695_15
  - libsanitizer=13.2.0=h6ddb7a1_7
  - libspatialite=5.1.0=h5539517_6
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=hceb6213_107
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - make=4.3=hd18ef5c_1
  - minizip=4.0.6=h9d307f2_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.5=h59595ed_0
  - nspr=4.35=h27087fc_0
  - nss=3.100=hca3bf56_0
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.0=h4ab18f5_3
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - pandoc=3.2=ha770c72_0
  - pango=1.52.2=ha41ecd1_0
  - pcre2=10.43=hcad00b1_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - poppler=24.04.0=hb6cd0d7_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.3=h8e811e2_0
  - proj=9.4.0=h1d62c97_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - r-abind=1.4_5=r42hc72bb7e_1005
  - r-askpass=1.2.0=r42h57805ef_0
  - r-base=4.2.3=hcf4f30c_13
  - r-base64enc=0.1_3=r42h57805ef_1006
  - r-bh=1.84.0_0=r42hc72bb7e_0
  - r-bitops=1.0_7=r42h57805ef_2
  - r-bslib=0.7.0=r42hc72bb7e_0
  - r-cachem=1.1.0=r42hb1dbf0f_0
  - r-catools=1.18.2=r42ha503ecb_2
  - r-cli=3.6.2=r42ha503ecb_0
  - r-cluster=2.1.6=r42h61816a4_0
  - r-codetools=0.2_20=r42hc72bb7e_0
  - r-colorspace=2.1_0=r42h57805ef_1
  - r-commonmark=1.9.1=r42h57805ef_0
  - r-cowplot=1.1.3=r42hc72bb7e_0
  - r-cpp11=0.4.7=r42hc72bb7e_0
  - r-crayon=1.5.2=r42hc72bb7e_2
  - r-crosstalk=1.2.1=r42hc72bb7e_0
  - r-curl=5.1.0=r42hf9611b0_0
  - r-data.table=1.15.2=r42h029312a_0
  - r-deldir=2.0_4=r42h61816a4_0
  - r-digest=0.6.35=r42ha503ecb_0
  - r-dotcall64=1.1_1=r42h61816a4_0
  - r-dplyr=1.1.4=r42ha503ecb_0
  - r-dqrng=0.3.2=r42ha503ecb_0
  - r-ellipsis=0.3.2=r42h57805ef_2
  - r-evaluate=0.23=r42hc72bb7e_0
  - r-fansi=1.0.6=r42h57805ef_0
  - r-farver=2.1.2=r42ha18555a_0
  - r-fastdummies=1.7.3=r42hc72bb7e_0
  - r-fastmap=1.2.0=r42ha18555a_0
  - r-fitdistrplus=1.1_11=r42hc72bb7e_1
  - r-fnn=1.1.4=r42ha503ecb_0
  - r-fontawesome=0.5.2=r42hc72bb7e_0
  - r-fs=1.6.4=r42ha18555a_0
  - r-future=1.33.2=r42h785f33e_0
  - r-future.apply=1.11.2=r42hc72bb7e_0
  - r-generics=0.1.3=r42hc72bb7e_2
  - r-ggplot2=3.5.1=r42hc72bb7e_0
  - r-ggrepel=0.9.5=r42ha503ecb_0
  - r-ggridges=0.5.6=r42hc72bb7e_0
  - r-globals=0.16.3=r42hc72bb7e_0
  - r-glue=1.7.0=r42h57805ef_0
  - r-goftest=1.2_3=r42h57805ef_2
  - r-gplots=3.1.3.1=r42hc72bb7e_0
  - r-gridextra=2.3=r42hc72bb7e_1005
  - r-gtable=0.3.5=r42hc72bb7e_0
  - r-gtools=3.9.5=r42h57805ef_0
  - r-here=1.0.1=r42hc72bb7e_2
  - r-hexbin=1.28.3=r42h61816a4_1
  - r-highr=0.11=r42hc72bb7e_0
  - r-htmltools=0.5.8.1=r42ha503ecb_0
  - r-htmlwidgets=1.6.4=r42hc72bb7e_1
  - r-httpuv=1.6.15=r42ha503ecb_0
  - r-httr=1.4.7=r42hc72bb7e_0
  - r-ica=1.0_3=r42hc72bb7e_2
  - r-igraph=2.0.3=r42hbec7d4a_0
  - r-irlba=2.3.5.1=r42h316c678_2
  - r-isoband=0.2.7=r42ha503ecb_2
  - r-jquerylib=0.1.4=r42hc72bb7e_2
  - r-jsonlite=1.8.8=r42h57805ef_0
  - r-kernsmooth=2.23_24=r42hc2011d3_0
  - r-knitr=1.47=r42hc72bb7e_0
  - r-labeling=0.4.3=r42hc72bb7e_0
  - r-later=1.3.2=r42ha503ecb_0
  - r-lattice=0.22_6=r42h57805ef_0
  - r-lazyeval=0.2.2=r42h57805ef_4
  - r-leiden=0.4.3.1=r42hc72bb7e_0
  - r-lifecycle=1.0.4=r42hc72bb7e_0
  - r-listenv=0.9.1=r42hc72bb7e_0
  - r-lmtest=0.9_40=r42h61816a4_2
  - r-lsei=1.3_0=r42hd8f1df9_3
  - r-magrittr=2.0.3=r42h57805ef_2
  - r-mass=7.3_60.0.1=r42h57805ef_0
  - r-matrix=1.6_5=r42h316c678_0
  - r-matrixstats=1.3.0=r42h57805ef_0
  - r-memoise=2.0.1=r42hc72bb7e_2
  - r-mgcv=1.9_1=r42h316c678_0
  - r-mime=0.12=r42h57805ef_2
  - r-miniui=0.1.1.1=r42hc72bb7e_1004
  - r-munsell=0.5.1=r42hc72bb7e_0
  - r-nlme=3.1_164=r42h61816a4_0
  - r-npsurv=0.5_0=r42hc72bb7e_2
  - r-openssl=2.2.0=r42hd7d0243_0
  - r-parallelly=1.37.1=r42h57805ef_0
  - r-patchwork=1.2.0=r42hc72bb7e_0
  - r-pbapply=1.7_2=r42hc72bb7e_0
  - r-pillar=1.9.0=r42hc72bb7e_1
  - r-pkgconfig=2.0.3=r42hc72bb7e_3
  - r-plotly=4.10.4=r42hc72bb7e_0
  - r-plyr=1.8.9=r42ha503ecb_0
  - r-png=0.1_8=r42h81d01c5_1
  - r-polyclip=1.10_6=r42ha503ecb_0
  - r-progressr=0.14.0=r42hc72bb7e_0
  - r-promises=1.3.0=r42ha503ecb_0
  - r-purrr=1.0.2=r42h57805ef_0
  - r-r6=2.5.1=r42hc72bb7e_2
  - r-rann=2.6.1=r42ha503ecb_4
  - r-rappdirs=0.3.3=r42h57805ef_2
  - r-raster=3.6_26=r42ha503ecb_0
  - r-rcolorbrewer=1.1_3=r42h785f33e_2
  - r-rcpp=1.0.12=r42h7df8631_0
  - r-rcppannoy=0.0.22=r42ha503ecb_0
  - r-rcpparmadillo=0.12.8.4.0=r42h58a4165_0
  - r-rcppeigen=0.3.4.0.0=r42h08d816e_0
  - r-rcpphnsw=0.6.0=r42ha503ecb_0
  - r-rcppprogress=0.4.2=r42hc72bb7e_3
  - r-rcpptoml=0.2.2=r42ha503ecb_1
  - r-reshape2=1.4.4=r42ha503ecb_3
  - r-reticulate=1.37.0=r42ha18555a_0
  - r-rlang=1.1.3=r42ha503ecb_0
  - r-rmarkdown=2.27=r42hc72bb7e_0
  - r-rocr=1.0_11=r42hc72bb7e_3
  - r-rprojroot=2.0.4=r42hc72bb7e_0
  - r-rspectra=0.16_1=r42h08d816e_2
  - r-rtsne=0.17=r42h7ce84a7_0
  - r-sass=0.4.9=r42ha503ecb_0
  - r-scales=1.3.0=r42hc72bb7e_0
  - r-scattermore=1.2=r42ha503ecb_1
  - r-sctransform=0.4.1=r42h08d816e_0
  - r-seurat=5.1.0=r42ha18555a_0
  - r-seuratobject=5.0.2=r42ha18555a_0
  - r-shiny=1.8.1.1=r42h785f33e_0
  - r-sitmo=2.0.2=r42ha503ecb_2
  - r-sourcetools=0.1.7_1=r42ha503ecb_1
  - r-sp=2.1_4=r42hb1dbf0f_0
  - r-spam=2.10_0=r42h9f9f741_0
  - r-spatstat.data=3.0_4=r42hc72bb7e_0
  - r-spatstat.explore=3.2_6=r42h57805ef_0
  - r-spatstat.geom=3.2_9=r42h57805ef_0
  - r-spatstat.random=3.2_3=r42ha503ecb_0
  - r-spatstat.sparse=3.0_3=r42h57805ef_0
  - r-spatstat.utils=3.0_4=r42h57805ef_0
  - r-stringi=1.8.4=r42hbd1cc82_0
  - r-stringr=1.5.1=r42h785f33e_0
  - r-survival=3.6_4=r42hb1dbf0f_0
  - r-sys=3.4.2=r42h57805ef_1
  - r-tensor=1.5=r42hc72bb7e_1005
  - r-terra=1.7_78=r42h4d71811_0
  - r-tibble=3.2.1=r42h57805ef_2
  - r-tidyr=1.3.1=r42ha503ecb_0
  - r-tidyselect=1.2.1=r42hc72bb7e_0
  - r-tinytex=0.51=r42hc72bb7e_0
  - r-utf8=1.2.4=r42h57805ef_0
  - r-uwot=0.1.16=r42ha503ecb_0
  - r-vctrs=0.6.5=r42ha503ecb_0
  - r-viridislite=0.4.2=r42hc72bb7e_1
  - r-withr=3.0.0=r42hc72bb7e_0
  - r-xfun=0.44=r42ha18555a_0
  - r-xtable=1.8_4=r42hc72bb7e_5
  - r-yaml=2.3.8=r42h57805ef_0
  - r-zoo=1.8_12=r42h57805ef_1
  - rasterio=1.3.10=py312h2447d21_1
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - s2n=1.4.15=he19d79f_0
  - scipy=1.13.1=py312hc2bc53b_0
  - sed=4.8=he412f7d_0
  - setuptools=70.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.0=hdb0a2a9_1
  - snuggs=1.4.7=py_0
  - spdlog=1.13.0=hd2e6256_0
  - sqlite=3.45.3=h2c6b66d_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tiledb=2.23.0=hfa691db_2
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - tzcode=2024a=h3f72095_0
  - tzdata=2024a=h0c530f3_0
  - uriparser=0.9.8=hac33072_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xerces-c=3.2.5=hac6953d_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - anndata==0.10.8
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/GDAL
