name: hicpeaks
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2016.9.26=py36_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgomp=13.2.0=h807b86a_5
  - libzlib=1.2.13=hd590300_5
  - ncurses=5.9=10
  - openssl=1.0.2u=h516909a_0
  - pip=20.0.2=py36_1
  - python=3.6.0=0
  - python_abi=3.6=2_cp36m
  - readline=6.2=0
  - setuptools=49.6.0=py36h5fab9bb_3
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.34.2=py36_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/hicpeaks
