name: ldsc
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bedtools=2.27.1=h9a82719_5
  - bitarray=0.8.1=py27_0
  - blas=1.0=mkl
  - certifi=2016.2.28=py27_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2017.0.3=0
  - nose=1.3.7=py27_1
  - openssl=1.0.2l=0
  - pip=9.0.1=py27_1
  - pybedtools=0.7.10=py27ha92aebf_3
  - pysam=0.8.4=py27_0
  - python=2.7.13=0
  - python-dateutil=2.6.1=py27_0
  - pytz=2017.2=py27_0
  - readline=6.2=2
  - setuptools=36.4.0=py27_1
  - six=1.10.0=py27_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.29.0=py27_0
  - zlib=1.2.11=0
  - pip:
      - numpy==1.16.0
      - pandas==0.20.0
      - scipy==0.18.0
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/ldsc
