name: meme
channels:
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - expat=2.2.10=he6710b0_2
  - ghostscript=9.18=1
  - icu=58.2=he6710b0_3
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - meme=5.0.5=py37pl526h19b89cf_0
  - mpi=1.0=openmpi
  - ncurses=6.4=h6a678d5_0
  - openmpi=4.0.2=hb1b8bf9_1
  - openssl=1.1.1u=h7f8727e_0
  - perl=5.26.2=h14c3975_0
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-base=2.23=pl526_1
  - perl-carp=1.38=pl526_3
  - perl-cgi=4.44=pl526h14c3975_1
  - perl-common-sense=3.74=pl526_2
  - perl-constant=1.33=pl526_1
  - perl-dbi=1.642=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-template=2.97=pl526_1
  - perl-html-tree=5.07=pl526_1
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-log-log4perl=1.49=pl526_0
  - perl-math-cdf=0.1=pl526h14c3975_5
  - perl-parent=0.236=pl526_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44=pl526h4e0c4b3_7
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.1.7=had09818_2
  - zlib=1.2.13=h5eee18b_0
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/meme
