name: neuronVis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.3=hcff3b4d_2
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - anyio==4.5.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.9
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.21.0
      - fonttools==4.55.0
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - fuzzywuzzy==0.18.0
      - glfw==2.8.0
      - h11==0.14.0
      - h5py==3.11.0
      - hsluv==5.0.4
      - httpcore==1.0.7
      - httpx==0.27.2
      - idna==3.10
      - igraph==0.11.8
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.4
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-rfb==0.3.3
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==1.1.11
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - molesq==0.4.0
      - morphops==0.1.13
      - navis==1.5.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ncollpyde==0.19.0
      - nest-asyncio==1.6.0
      - networkx==3.1
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.24.4
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pint==0.21.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==5.24.1
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pyglm==2.7.3
      - pygments==2.18.0
      - pynrrd==1.1.1
      - pyopengl==3.1.7
      - pyparsing==3.1.4
      - pypng==0.20220715.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.15.0
      - python-dateutil==2.9.0.post0
      - python-igraph==0.11.8
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rdata==0.9
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - send2trash==1.8.0
      - six==1.16.0
      - skeletor==1.2.0
      - sniffio==1.3.1
      - soupsieve==2.3.2
      - stack-data==0.6.3
      - tenacity==8.0.1
      - terminado==0.13.3
      - texttable==1.6.4
      - threadpoolctl==3.1.0
      - tinycss2==1.1.1
      - tomli==2.2.1
      - tornado==6.4.2
      - tqdm==4.64.0
      - traitlets==5.14.3
      - trimesh==4.5.3
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.1.1
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==1.26.9
      - vispy==0.14.2
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==3.6.0
      - xarray==0.20.2
      - zipp==3.8.0
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/neuronVis
