name: py38
channels:
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - libedit=3.1.20221030=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=66.0.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - asciitree==0.3.3
      - asttokens==2.2.1
      - backcall==0.2.0
      - bioframe==0.6.1
      - biopython==1.81
      - blosc2==2.0.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.3
      - contourpy==1.0.7
      - cooler==0.9.3
      - cooltools==0.7.1
      - cycler==0.11.0
      - cython==0.29.34
      - cytoolz==0.12.1
      - decorator==5.1.1
      - deprecated==1.2.13
      - dill==0.3.6
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fonttools==4.39.3
      - future==0.18.3
      - h5py==3.8.0
      - hic2cool==0.5.1
      - hicexplorer==2.2.1.1
      - hicmatrix==7
      - hicrep==0.2.6
      - idna==3.6
      - imageio==2.33.1
      - importlib-metadata==7.0.1
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - intervaltree==2.1.0
      - ipython==8.12.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.4
      - krbalancing==0.5.0b0
      - lazy-loader==0.3
      - llvmlite==0.41.1
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - msgpack==1.0.5
      - multiprocess==0.70.14
      - networkx==3.1
      - numba==0.58.1
      - numexpr==2.8.4
      - numpy==1.24.4
      - packaging==23.1
      - pandas==1.5.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pluggy==1.0.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pybigwig==0.3.22
      - pyfaidx==0.7.2.1
      - pygenometracks==3.0
      - pygments==2.15.1
      - pypairix==0.3.7
      - pyparsing==3.0.9
      - pysam==0.21.0
      - pytest==7.3.1
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - requests==2.31.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - simplejson==3.19.1
      - six==1.16.0
      - sortedcontainers==2.4.0
      - stack-data==0.6.2
      - tables==3.8.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - tomli==2.0.1
      - toolz==0.12.0
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - unidecode==1.3.6
      - urllib3==2.2.0
      - wcwidth==0.2.6
      - wrapt==1.15.0
      - zipp==3.15.0
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/py38
