name: py3hapcut2
channels:
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bcftools=1.8=h4da6232_3
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - curl=7.87.0=h5eee18b_0
  - hapcut2=1.3.3=h22771d5_0
  - htslib=1.12=h9093b5e_1
  - krb5=1.19.4=h568e23c_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.87.0=h91b91d3_0
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - pysam=0.11.2.2=py36_1
  - python=3.6.13=h12debd9_1
  - readline=8.2=h5eee18b_0
  - samtools=1.6=hb116620_7
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/py3hapcut2
