name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - brotli-python=1.1.0=py312h2ec8cdc_3
  - bwa=0.7.19=h577a1d6_1
  - bwidget=1.10.1=ha770c72_1
  - bx-python=0.13.0=py312h5e9d817_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.7.9=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.7.9=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - coin-or-cbc=2.10.12=h00e76a6_2
  - coin-or-cgl=0.60.9=h82e2f02_4
  - coin-or-clp=1.17.10=h8a7a1e7_1
  - coin-or-osi=0.108.11=h96cc833_4
  - coin-or-utils=2.11.12=h3a12e53_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - curl=8.14.1=h332b0f4_0
  - cutadapt=5.1=py312h0fa9677_0
  - dnaio=1.2.2=py312hf67a6ed_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - fastqc=0.12.1=hdfd78af_0
  - flash=1.2.11=0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_3
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_3
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - graphite2=1.3.14=h5888daf_0
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.1.0=h6a1bac1_3
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.22=h566b1c6_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - immutables=0.21=py312h66e93f0_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - isa-l=2.31.1=hb9d3cd8_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=15.1.0=h4c094af_103
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libglib=2.84.2=h3618099_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblapacke=3.9.0=32_he2f377e_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libpng=1.6.50=h943b412_0
  - libsanitizer=15.1.0=h97b714f_3
  - libsqlite=3.50.2=h6cd9bfd_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_103
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - logmuse=0.2.8=pyhd8ed1ab_1
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h178313f_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.1=py312h6cf2f7f_0
  - openjdk=23.0.2=h53dfc1b_2
  - openssl=3.5.1=h7b32b05_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py312hf9745cd_0
  - pango=1.56.4=hadf4263_0
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.45=hc749103_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - perl=5.32.1=7_hd590300_perl5
  - pigz=2.8=hadc24fc_1
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulp=2.8.0=py312hd0750ca_2
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312hc6f7160_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysam=0.23.0=py312h47d5410_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.1=pyhd8ed1ab_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-isal=1.7.2=py312h66e93f0_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-zlib-ng=0.5.1=py312h27ca174_0
  - python_abi=3.12=6_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - r-base=4.4.3=h85845a0_2
  - r-cli=3.6.5=r44h93ab643_0
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-ggplot2=3.5.2=r44hc72bb7e_0
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-isoband=0.2.7=r44ha18555a_3
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_7=r44h2b5f3a1_0
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_3=r44h2ae2be5_0
  - r-mgcv=1.9_3=r44h2ae2be5_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_168=r44hb67ce94_0
  - r-patchwork=1.3.1=r44hc72bb7e_0
  - r-pillar=1.11.0=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-plotrix=3.8_4=r44hc72bb7e_1
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rlang=1.1.6=r44h93ab643_0
  - r-scales=1.4.0=r44hc72bb7e_0
  - r-tibble=3.3.0=r44h2b5f3a1_0
  - r-utf8=1.2.6=r44h2b5f3a1_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.26.0=py312h680f630_0
  - samtools=1.22=h96c455f_0
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - slack-sdk=3.35.0=pyhd8ed1ab_0
  - slack_sdk=3.35.0=hd8ed1ab_0
  - smart_open=7.3.0=pyhe01879c_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=9.6.2=hdfd78af_0
  - snakemake-interface-common=1.20.0=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.7=pyhdfd78af_0
  - snakemake-interface-logger-plugins=1.2.3=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.1.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=4.2.1=pyhdfd78af_0
  - snakemake-minimal=9.6.2=pyhdfd78af_0
  - star=2.7.11b=h5ca1c30_6
  - sysroot_linux-64=2.12=he073ed8_17
  - tabulate=0.9.0=pyhd8ed1ab_2
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tomli=2.2.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.16.0=pyh167b9f4_0
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py312h66e93f0_0
  - xopen=2.0.2=pyh707e725_2
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yaml=0.2.5=h7f98852_2
  - yte=1.8.1=pyha770c72_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
prefix: /data/home/ruanlab/huangxingyu/miniconda3/envs/snakemake
